{
  imports = [
    ./autoCpuFreq.nix
    ./bluetooth.nix
    ./boot.nix
    ./docker.nix
    ./env.nix
    ./firmware.nix
    ./fonts.nix
    ./graphics.nix
    ./mysql.nix
    ./nixSettings.nix
    ./sound.nix
    ./systemdServices.nix
    ./udevRules.nix
    ./user.nix
    ./xdgPortal.nix
  ];
}
